SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `Java2_test` DEFAULT CHARACTER SET utf8 ;
USE `Java2_test` ;

-- -----------------------------------------------------
-- Table `Java2_test`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java2_test`.`addresses` ;

CREATE TABLE IF NOT EXISTS `java2_test`.`addresses` (
  `AddressID` INT(11) NOT NULL AUTO_INCREMENT,
  `ClientID` INT(11) NOT NULL,
  `Country` CHAR(32) NOT NULL,
  `City` CHAR(32) NOT NULL,
  `Street` CHAR(32) NOT NULL,
  `House` INT(11) NOT NULL,
  `Flat` INT(11) NOT NULL,
  `Postcode` CHAR(7) NOT NULL,
  PRIMARY KEY (`AddressID`)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1002;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;